name: CI/CD

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_msvc2019'
          dir: '${{github.workspace}}/qt/'
      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -AWin32 -DQt5_DIR=${{env.Qt5_DIR}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2
      - name: Prepare artifacts
        run: |
          mkdir bin
          mv build/bin/HLAM.exe bin
          mv build/bin/glew-shared.dll bin
          mv build/bin/OpenAL32.dll bin
          mv build/bin/Qt5Core.dll bin
          mv build/bin/Qt5Gui.dll bin
          mv build/bin/Qt5Network.dll bin
          mv build/bin/Qt5Widgets.dll bin
          mv build/bin/imageformats bin/imageformats
          mv build/bin/platforms bin/platforms
          mv build/bin/styles bin/styles
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Win32
          path: |
            bin
