name: CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  BUILD_TYPE: RelWithDebInfo
  VCPKG_ROOT: ${{github.workspace}}/vcpkg

jobs:
  linux:
    name: Linux-x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
         
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '${{github.workspace}}/qt/'
          
      - uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{env.VCPKG_ROOT}}'
          runVcpkgInstall: false
          vcpkgJsonIgnores: "['**/vcpkg/**', '**/vcpkg_config/**']"
         
      - name: Configure
        run: >
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DQt5_DIR=${{env.Qt5_DIR}}
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2
      
#      - name: Prepare artifacts
#        run: |
#          mkdir bin
#          mv build/bin/HLAM bin
#          mv build/bin/libopenal.so.1.22.2 bin
#          mv build/bin/libQt5Core.so.5.15.2 bin
#          mv build/bin/libQt5Gui.so.5.15.2 bin
#          mv build/bin/libQt5Network.so.5.15.2 bin
#          mv build/bin/libQt5Widgets.so.5.15.2 bin
#          mv build/bin/imageformats bin/imageformats
#          mv build/bin/platforms bin/platforms
#      
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: Linux-x64
#          path: |
#            bin

  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_msvc2019'
          dir: '${{github.workspace}}/qt/'
      
      - uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{env.VCPKG_ROOT}}'
          runVcpkgInstall: false
          vcpkgJsonIgnores: "['**/vcpkg/**', '**/vcpkg_config/**']"
      
      - name: Configure
        run: >
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DQt5_DIR=${{env.Qt5_DIR}}
          -A Win32
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2
      
      - name: Prepare artifacts
        run: |
          mkdir bin
          mv build/bin/HLAM.exe bin
          mv build/bin/OpenAL32.dll bin
          mv build/bin/Qt5Core.dll bin
          mv build/bin/Qt5Gui.dll bin
          mv build/bin/Qt5Network.dll bin
          mv build/bin/Qt5Widgets.dll bin
          mv build/bin/imageformats bin/imageformats
          mv build/bin/platforms bin/platforms
          mv build/bin/styles bin/styles
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Win32
          path: |
            bin
